
language: go

branches:
  only:
    - blog  # 设置自动化部署的源码分支
    - 2-travis-auto-depoly # test for travis

# cache this directory
cache:
  directories:
    - themes
    # - public
    #- themes 主题没有更改时可以缓存

before_install:
- export TZ='Asia/Shanghai'  # 设置时区
  #- npm install -g hexo
  #- npm install -g hexo-cli

# 安装依赖组件
install:
#  - wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.tar.gz
  - wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_extended_0.80.0_Linux-64bit.tar.gz #扩展版本支持scss
  - tar -xzvf hugo_extended_0.80.0_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
    #- git clone -b ${TRAVIS_BRANCH} --recursive https://github.com/m2kar.github.io.git
    #- cd m2kar.github.io
  - git log -p -2 | cat
#  - commit_msg=$(git log -n1 --pretty=format:"%s")
  - rm -rf public/*
#  - git clone --recursive -b master https://oauth2:${GH_APIKEY2}@github.com/caoyanbin1993/anson.github.io.git public

script:
  - hugo  --enableGitInfo
#  - cp CNAME public/
#  - pushd public 
#  - git add .
#  - git commit -m "auto depoly ${commit_msg} "
#  - git push
#  - echo "depoly done"

  # 构建完成后会自动更新Github Pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GH_APIKEY2
  keep-history: true
  on:
    branch: blog